spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.vlqhpozfotcygtpgmzta
spring.datasource.password=10keMzUmCQ7Hl5U1
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}

# File upload (from your old config)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# JWT (from your old config)
jwt.secret=this_is_your_very_secure_secret_key_123456
